[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 1
padding.y = 1
decorations = "Transparent"
opacity = 0.90

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
